import {describe,expect,it} from 'vitest';
import {buildEvidenceBundle,buildSyntheticHistory} from '../worker/domain';
import {bestSources,COUNCIL_ADVISORS,COUNCIL_JSON_SCHEMA,COUNCIL_MODEL,councilPrompt,hydrateStructuredCouncil,runWorkersAiCouncil} from '../worker/model';
const bundle=()=>buildEvidenceBundle('Priya message website rejection client work',buildSyntheticHistory());
const raw=()=>({situationSummary:'Maya has a prepared message for Priya and keeps choosing website work instead.',rememberedFacts:[{text:'Priya message remained unsent after a morning of website work.',personalSlots:['P1']},{text:'A protected first action has helped Maya follow through before.',personalSlots:['P2']}],interpretations:['This may be avoidance of an exposing answer, not lack of interest.'],centralConflict:'Maya wants a real answer while also wanting protection from rejection.',competingDuties:['Serve existing clients honestly','Test the new service directly'],unknowns:['Consilium cannot know how Priya will answer.'],rejectedInferences:['An unsent message does not prove Maya is incapable.'],reports:{'marcus-aurelius':{scope:'Present duty and honest conduct now.',sourceApplication:'The supplied present-time passage directs attention to the real moment.',limitation:'It cannot predict Priya or erase fear.',reasoning:'The prepared ask is the honest duty already in front of Maya.',counsel:'At 9:00, face the present duty by sending the current draft.',uncertainty:'Priya may decline.',confidence:.75,abstain:false,personalSlots:['P1','P2'],sourceSlots:['S1']},epictetus:{scope:'Agency and the boundary around another person’s answer.',sourceApplication:'The supplied passage distinguishes Maya’s act from Priya’s reply.',limitation:'Non-control does not make the reply unimportant.',reasoning:'Maya can choose a clear ask but cannot choose its reception.',counsel:'Send the clear message; leave Priya free to answer.',uncertainty:'The answer is outside Maya’s agency.',confidence:.8,abstain:false,personalSlots:['P1'],sourceSlots:['S1']},'sun-tzu':{scope:'Work conditions, timing, and divided effort only.',sourceApplication:'The supplied passage supports choosing conditions before effort disperses.',limitation:'This military analogy does not interpret emotion or relationships.',reasoning:'The quiet first block has worked better than opening more fronts.',counsel:'Before opening the website, use the prepared short message.',uncertainty:'One good condition does not guarantee follow-through.',confidence:.72,abstain:false,personalSlots:['P1','P2'],sourceSlots:['S1']}},tensions:['Marcus stresses duty; Epictetus protects against self-condemnation; Sun Tzu only changes conditions.'],synthesis:{belief:'Maya appears to be using tidy website work to avoid an exposing answer.',rationale:'A direct ask fits the goal, while protected first actions have helped before.',rejectedAlternative:'Do not redesign the website first.',clinicalBoundary:'Philosophical advice is not treatment for depression or a replacement for human support.',immediateAction:'Tomorrow at 9:00, before opening the website, send Priya the current short message.',followUp:'After Priya replies, record what happened without treating her answer as a verdict on Maya.',unapproved:'This action is proposed only; no plan has changed.'}});
describe('deep structured council',()=>{
 it('uses one bounded 70B JSON call',async()=>{let calls=0;const ai={run:(model:typeof COUNCIL_MODEL,input:Record<string,unknown>)=>{calls++;expect(model).toBe('@cf/meta/llama-3.3-70b-instruct-fp8-fast');expect(input.response_format).toEqual({type:'json_schema',json_schema:COUNCIL_JSON_SCHEMA});return Promise.resolve({response:raw()})}};expect((await runWorkersAiCouncil(ai,bundle())).reports).toHaveLength(3);expect(calls).toBe(1)});
 it('includes structured human context and hides server identifiers',()=>{const prompt=JSON.stringify(councilPrompt(bundle()));expect(prompt).toContain('warm potential client Priya');expect(prompt).toContain('author');expect(prompt).toContain('relationship');expect(prompt).not.toContain('evt-45-priya-draft')});
 it('hydrates only explicitly selected server-owned slots',()=>{const result=hydrateStructuredCouncil(raw(),bundle());expect(result.reasoningRecord.unknowns).toHaveLength(1);for(const report of result.reports){expect(report.claims[0]!.personalEvidenceIds.length).toBeGreaterThan(0);expect(report.claims[0]!.advisorEvidenceIds.length).toBe(1)}});
 it('rejects unknown and cross-lane slots',()=>{const bad=raw();bad.reports.epictetus.sourceSlots=['S99'];expect(()=>hydrateStructuredCouncil(bad,bundle())).toThrow('UNSUPPORTED_EVIDENCE_SLOT')});
 it('uses query relevance, not only a static score',()=>{const sources=bundle().sourceByAdvisor.epictetus!;expect(bestSources('power acts control',sources)[0]?.id).toBe('epictetus-ench-01a')});
 it('keeps fixed advisor set',()=>expect(COUNCIL_JSON_SCHEMA.properties.reports.required).toEqual(COUNCIL_ADVISORS));
});
