import {describe,expect,it} from 'vitest';
import {buildEvidenceBundle,buildSyntheticHistory,synthesize} from '../worker/domain';
import {bestSources,selectPersonalEvidence} from '../worker/model';
import {imminentRisk} from '../worker/index';
import {validateReflection} from '../worker/reflection';

describe('Pass 8 human continuity and council depth',()=>{
 it('keeps the concrete cross-area story coherent',()=>{const h=buildSyntheticHistory(),joined=h.map(x=>`${x.area} ${x.relationship} ${x.text} ${x.outcome}`).join(' ');for(const terms of [/vocational.*Priya.*message.*website.*scared/i,/social.*mother.*house.*cried.*dementia/i,/client.*said yes.*shoulders.*evening/i,/physical.*phone.*walked.*calmer.*finished/i,/financial.*renewal.*two months.*cancelled/i])expect(joined).toMatch(terms);expect(h.every(x=>x.author==='maya')).toBe(true)});
 it('contains ordinary scene, feeling or body, context, and consequence across all six areas',()=>{const h=buildSyntheticHistory();for(const area of ['physical','mental','spiritual','social','financial','vocational']){const rows=h.filter(x=>x.area===area);expect(rows.length,area).toBeGreaterThan(0);expect(rows.some(x=>/I |my |Mum|Priya/i.test(x.text)&&Boolean(x.outcome)),area).toBe(true)}expect(h.map(x=>x.text).join(' ')).not.toMatch(/pilot invitation|evidence-led|fixture|test record|coverage/i)});
 it('does not leak pilot-only context into a Mum and house-sale question',()=>{const b=buildEvidenceBundle('Mum dementia house sale guilt',buildSyntheticHistory());expect(b.history.some(x=>x.tags.includes('mum'))).toBe(true);expect(b.history[0]?.text).not.toContain('pilot invitation')});
 it('selects advisor evidence by the actual question and keeps Sun Tzu on conditions',()=>{const b=buildEvidenceBundle('Mum dementia house sale depression workload',buildSyntheticHistory());const sun=selectPersonalEvidence(b,'sun-tzu');expect(sun.some(x=>/work|client|capacity|focus/i.test(`${x.text} ${x.outcome}`))).toBe(true);const irrelevant={...b.sourceByAdvisor['sun-tzu']![0]!,id:'keyword-trap',text:'Depression grief dementia mother',retrievalScore:.99};expect(bestSources('fight conditions',[irrelevant,...b.sourceByAdvisor['sun-tzu']!])[0]?.id).not.toBe('keyword-trap')});
 it('synthesizes the whole validated council rather than returning advisor one',()=>{const b=buildEvidenceBundle('Priya website message',buildSyntheticHistory()),reports=[] as never[];expect(synthesize(b,reports).abstained).toBe(true)});
 it('routes only explicit imminent danger to the deterministic gate',()=>{expect(imminentRisk('I have depression and work feels overwhelming')).toBe(false);expect(imminentRisk('I cannot stay safe and may hurt myself')).toBe(true)});
 it('retrieves the linked serious-advice areas instead of pilot-only events',()=>{const b=buildEvidenceBundle('Mum dementia clinic family house sale depression overwhelming work love guilt grief money capacity',buildSyntheticHistory());expect(b.history.map(item=>item.area)).toEqual(expect.arrayContaining(['social','mental','vocational','financial','spiritual']));expect(b.history.some(item=>item.tags.includes('counterexample'))).toBe(true);expect(b.history.some(item=>item.tags.includes('pilot'))).toBe(false)});
 it('accepts natural CAAR paraphrases without magic vocabulary',()=>{const input={journal:'Today held useful work and an uncomfortable question that I kept avoiding until the day ended.',biometrics:{sleep_hours:7,energy_level:6,stress_level:6},caar:{q1_today_intent:'The note was my aim; the draft is as far as I got.',q2_top_win:'The client review reached a good stopping point through a noisy afternoon.',q3_top_failure:'The note stayed on my screen while I kept polishing the easier page.',q4_pattern_notice:'Exposed conversations often give way to tidier tasks; deadlines have broken that tendency.',q5_tomorrow_priority:'Send the short note to Priya ahead of everything else.',q6_if_then_plan:'On reaching for the website editor, I switch to Priya’s draft and press send.'},goal_reflections:[{goal_id:'goal',status:'achieved'}]};expect(validateReflection(input).ok).toBe(true)});
});
