import {describe,expect,it} from 'vitest';
import {buildEvidenceBundle,buildSyntheticHistory,synthesize} from '../worker/domain';
import {bestSources,selectPersonalEvidence} from '../worker/model';
import {imminentRisk} from '../worker/index';
import {validateReflection} from '../worker/reflection';

describe('Pass 8 human continuity and council depth',()=>{
 it('keeps the concrete cross-area story coherent',()=>{const h=buildSyntheticHistory(),joined=h.map(x=>`${x.area} ${x.relationship} ${x.text} ${x.outcome}`).join(' ');for(const terms of [/vocational.*Priya.*message.*website.*scared/i,/social.*mother.*house.*cried.*dementia/i,/client.*said yes.*shoulders.*evening/i,/physical.*phone.*walked.*calmer.*finished/i,/financial.*renewal.*two months.*cancelled/i])expect(joined).toMatch(terms);expect(h.every(x=>x.author==='maya')).toBe(true)});
 it('contains ordinary scene, feeling or body, context, and consequence across all six areas',()=>{const h=buildSyntheticHistory();for(const area of ['physical','mental','spiritual','social','financial','vocational']){const rows=h.filter(x=>x.area===area);expect(rows.length,area).toBeGreaterThan(0);expect(rows.some(x=>/I |my |Mum|Priya/i.test(x.text)&&Boolean(x.outcome)),area).toBe(true)}expect(h.map(x=>x.text).join(' ')).not.toMatch(/pilot invitation|evidence-led|fixture|test record|coverage/i)});
 it('does not leak pilot-only context into a Mum and house-sale question',()=>{const b=buildEvidenceBundle('Mum dementia house sale guilt',buildSyntheticHistory());expect(b.history.some(x=>x.tags.includes('mum'))).toBe(true);expect(b.history[0]?.text).not.toContain('pilot invitation')});
 it('selects advisor evidence by the actual question and keeps Sun Tzu on conditions',()=>{const b=buildEvidenceBundle('Mum dementia house sale depression workload',buildSyntheticHistory());const sun=selectPersonalEvidence(b,'sun-tzu');expect(sun.some(x=>/work|client|capacity|focus/i.test(`${x.text} ${x.outcome}`))).toBe(true);const irrelevant={...b.sourceByAdvisor['sun-tzu']![0]!,id:'keyword-trap',text:'Depression grief dementia mother',retrievalScore:.99};expect(bestSources('fight conditions',[irrelevant,...b.sourceByAdvisor['sun-tzu']!])[0]?.id).not.toBe('keyword-trap')});
 it('synthesizes the whole validated council rather than returning advisor one',()=>{const b=buildEvidenceBundle('Priya website message',buildSyntheticHistory()),reports=[] as never[];expect(synthesize(b,reports).abstained).toBe(true)});
 it('routes only explicit imminent danger to the deterministic gate',()=>{expect(imminentRisk('I have depression and work feels overwhelming')).toBe(false);expect(imminentRisk('I cannot stay safe and may hurt myself')).toBe(true)});
 it('retrieves the linked serious-advice areas instead of pilot-only events',()=>{const b=buildEvidenceBundle('Mum dementia clinic family house sale depression overwhelming work love guilt grief money capacity',buildSyntheticHistory());expect(b.history.map(item=>item.area)).toEqual(expect.arrayContaining(['social','mental','vocational','financial','spiritual']));expect(b.history.some(item=>item.tags.includes('counterexample'))).toBe(true);expect(b.history.some(item=>item.tags.includes('pilot'))).toBe(false)});
 it('rejects schema-valid answers placed under the wrong reflection questions',()=>{const input={journal:'Today held useful work and an uncomfortable question that I kept avoiding until the day ended.',biometrics:{sleep_hours:7,energy_level:6,stress_level:6},caar:{q1_today_intent:'Today I intended to send the note, but I only drafted it.',q2_top_win:'I did not send it because the website felt safer instead.',q3_top_failure:'My win was finishing the review despite checking my phone.',q4_pattern_notice:'My one priority tomorrow is to send the note first.',q5_tomorrow_priority:'I may polish when afraid, but urgency can help me act.',q6_if_then_plan:'If I open the website, then I will send the note first.'},goal_reflections:[{goal_id:'goal',status:'achieved'}]};const result=validateReflection(input);expect(result.ok).toBe(false);if(!result.ok)for(const key of ['q2_top_win','q3_top_failure','q4_pattern_notice','q5_tomorrow_priority'])expect(result.fieldErrors[`caar.${key}`]).toMatch(/meaning/)});
});
