import { readFileSync } from 'node:fs';
import { DatabaseSync, type StatementSync } from 'node:sqlite';
import { describe,expect,it } from 'vitest';
import worker from '../worker/index';

class SqliteStatement {
  private parameters:string[]=[];
  constructor(private readonly statement:StatementSync,readonly reads:boolean){}
  bind(...parameters:unknown[]){this.parameters=parameters.map(String);return this}
  run(){const result=this.statement.run(...this.parameters);return Promise.resolve({success:true,meta:{changes:Number(result.changes)},results:[]})}
  first<T>(){return Promise.resolve(this.statement.get(...this.parameters) as T|null)}
  all<T>(){return Promise.resolve({success:true,meta:{changes:0},results:this.statement.all(...this.parameters) as T[]})}
}

class SqliteD1 {
  constructor(private readonly database:DatabaseSync){}
  prepare(sql:string){return new SqliteStatement(this.database.prepare(sql),/^\s*SELECT\b/i.test(sql))}
  async batch(statements:SqliteStatement[]){const results=[];for(const statement of statements)results.push(statement.reads?await statement.all():await statement.run());return results}
}

const generatedInterpretation=(advisor:string,lens:string)=>({scope:`The ${lens} scope is deliberately bounded to its legitimate dimension.`,sourceApplication:'The supplied passage is applied to the question rather than used decoratively.',limitation:'This passage cannot predict outcomes or replace human support.',reasoning:`The ${lens} lens considers the retrieved scene and its recorded outcome.`,counsel:`Use the ${lens} lens for one small proposed next step.`,uncertainty:'The canonical history cannot guarantee an external reply.',confidence:.77,abstain:false,personalSlots:[`${advisor}:P1`],counterPersonalSlots:[],sourceSlots:[`${advisor}:S1`]});
const generatedCouncil=()=>({situationSummary:'Maya is balancing an exposed decision with existing client work and limited capacity.',rememberedFacts:[{text:'The retrieved scene records a difficult action and its consequence.',personalSlots:['marcus-aurelius:P1']},{text:'The retrieved history contains an earlier relevant attempt.',personalSlots:['sun-tzu:P2']}],interpretations:['The pattern may involve avoiding rejection through safer work.'],centralConflict:'An honest exposed action competes with safety and existing obligations.',competingDuties:['Care for existing responsibilities','Make room for the new decision'],unknowns:['The evidence cannot predict another person’s response.'],rejectedInferences:['Avoidance does not prove lack of care or ability.'],reports:{'marcus-aurelius':generatedInterpretation('marcus-aurelius','present-duty'),epictetus:generatedInterpretation('epictetus','controllable-agency'),'sun-tzu':generatedInterpretation('sun-tzu','work-conditions')},tensions:['Duty, agency, and workload conditions point to different limits.'],synthesis:{belief:'The safest work may be crowding out the action that would answer the real question.',rationale:'The retrieved history supports a bounded first action while preserving uncertainty.',rejectedAlternative:'Do not add more preparation merely to avoid exposure.',clinicalBoundary:'Philosophical advice is not treatment for depression or a replacement for human support.',immediateAction:'Take one small action from the prepared material before opening more work.',followUp:'Record what happened afterward.',unapproved:'Nothing has been applied without explicit consent.'}});
class CloudflareAiFixture {embeddingCalls:string[][]=[];run(model:string,input:{text?:string[]}):Promise<unknown>{if(model==='@cf/openai/gpt-oss-20b')return Promise.resolve({response:generatedCouncil()});const texts=input.text??[];this.embeddingCalls.push(texts);return Promise.resolve({data:texts.map(text=>Array.from({length:768},(_,dimension)=>dimension===0?(text.includes('marcus-aurelius')?2:text.includes('epictetus')?3:text.includes('sun-tzu')?4:1):.01))})}}
class InvalidCouncilAiFixture extends CloudflareAiFixture {override run(model:string,input:{text?:string[]}){if(model==='@cf/openai/gpt-oss-20b'){const invalid=generatedCouncil();invalid.reports['sun-tzu'].counsel='Treat depression and grief as a battle and suppress the guilt.';return Promise.resolve({response:invalid})}return super.run(model,input)}}
class MalformedCouncilAiFixture extends CloudflareAiFixture {override run(model:string,input:{text?:string[]}){if(model==='@cf/openai/gpt-oss-20b')return Promise.resolve({response:{situationSummary:7,reports:{}}});return super.run(model,input)}}
class VectorizeFixture {
  private ids:string[]=[];
  constructor(private readonly personalMatches?:string[]){}
  upsert(vectors:{id:string}[]){this.ids=vectors.map(vector=>vector.id);return Promise.resolve({mutationId:'fixture-mutation'})}
  query(_vector:number[],options:{topK:number;filter:Record<string,string>}){const filter=options.filter;let ids:string[]=[];if(filter.corpus_kind==='personal')ids=this.personalMatches?.map(id=>`vec-${id}`)??this.ids.filter(id=>id.startsWith('vec-evt-')).slice(0,8);else if(filter.advisor_id==='marcus-aurelius')ids=['vec-marcus-b4-03','vec-marcus-b2-15'];else if(filter.advisor_id==='epictetus')ids=['vec-epictetus-ench-01a','vec-epictetus-ench-01b'];else if(filter.advisor_id==='sun-tzu')ids=['vec-suntzu-3-2','vec-suntzu-1-18'];return Promise.resolve({matches:ids.filter(id=>this.ids.includes(id)).slice(0,options.topK).map(id=>({id,score:.9})),count:Math.min(ids.length,options.topK)})}
}

const baseEnv=(database:DatabaseSync)=>({DB:new SqliteD1(database),MODEL_CONFIG_VERSION:'council-v1',PIPELINE_VERSION:'0f7f47a4116e02d59f2622824e4535cda5c92ffa2eb0648deda04bd72309bed5',CONSULTATION_LIMIT_PER_HOUR:'6',SESSION_KEY_VERSION:'k1',SESSION_SIGNING_KEY:'test-only-signing-secret-at-least-32-bytes',ASSETS:{fetch:()=>Promise.resolve(new Response('asset'))}});
const migratedDatabase=()=>{const database=new DatabaseSync(':memory:');for(const file of ['0001_initial.sql','0002_hardening.sql','0003_recovery_product.sql','0004_structured_reflection.sql','0005_exact_life_domains.sql','0006_pass5_journal_commit.sql'])database.exec(readFileSync(`migrations/${file}`,'utf8'));return database};
const reflectionInput=(todayIds:string[],marker='outreach')=>({journal:`A deliberately specific ${marker} journal records the operational and emotional tone of this day.`,biometrics:{sleep_hours:6.5,energy_level:6,stress_level:7,resting_hr:61},caar:{q1_today_intent:`Today I intended to finish the ${marker} task, but I completed only the preparation.`,q2_top_win:`My win was finishing the client review despite the difficult pull to check messages.`,q3_top_failure:`I did not send the ${marker} note because fear made comfortable polishing feel safer.`,q4_pattern_notice:`I may avoid exposed ${marker} when I fear an answer, but urgency has also helped me act directly.`,q5_tomorrow_priority:`My one priority tomorrow is to complete the ${marker} action first.`,q6_if_then_plan:`If avoidance appears tomorrow, then I will send one plain ${marker} test before polishing.`},goal_reflections:todayIds.map((goal_id,index)=>({goal_id,status:index===0?'missed':'achieved',...(index===0?{why_failed:`I avoided the exposed ${marker} action and chose comfortable polishing instead.`,adaptation:`Open the ${marker} target first and complete one plain attempt before any polishing.`}:{})}))});

describe('first-request D1 seed',()=>{
  it('persists the recovered mission → failure → reflection → brief loop on one session',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'fixture'};
    const initial=await worker.fetch(new Request('https://fixture.test/api/product'),env as never),cookie=initial.headers.get('set-cookie')?.split(';')[0],product=await initial.json<{areas:{id:string}[];missions:unknown[]}>();
    expect({status:initial.status,areas:product.areas.length,missions:product.missions.length}).toEqual({status:200,areas:6,missions:12});
    const call=async(path:string,input:unknown)=>worker.fetch(new Request(`https://fixture.test${path}`,{method:'POST',headers:{cookie:cookie!,'content-type':'application/json'},body:JSON.stringify(input)}),env as never);
    const created=await call('/api/missions',{kind:'goal',areaId:product.areas[0]!.id,horizon:'today',title:'Unique recovery goal',why:'Prove linked history'}),mission=await created.json<{id:string}>();
    expect(created.status).toBe(201);
    expect((await call('/api/progress',{missionId:mission.id,result:'failure',progress:10,note:'The first attempt failed'})).status).toBe(201);
    const refreshed=await (await worker.fetch(new Request('https://fixture.test/api/product',{headers:{cookie:cookie!}}),env as never)).json<{missions:{id:string;horizon:string;status:string}[]}>(),todayIds=refreshed.missions.filter(item=>item.horizon==='today'&&item.status==='active').map(item=>item.id);
    const submitted=reflectionInput(todayIds,'contact-list'),reflected=await call('/api/reflections',submitted),reflection=await reflected.json<{id:string}>();
    expect(reflected.status).toBe(201);
    const stored=database.prepare('SELECT caar_json FROM nightly_reflections WHERE id=?').get(reflection.id) as {caar_json:string},facts=database.prepare('SELECT fact_type,fact_text,source_key FROM reflection_facts WHERE reflection_id=? ORDER BY source_key').all(reflection.id) as {fact_type:string;fact_text:string;source_key:string}[];
    const caarFacts=facts.filter(fact=>fact.source_key.startsWith('q'));expect(JSON.parse(stored.caar_json)).toEqual(submitted.caar);expect(caarFacts.map(fact=>fact.fact_type)).toEqual(['progress','success','friction','misalignment','mission','adaptation']);expect(caarFacts.map(fact=>fact.fact_text)).toEqual(Object.values(submitted.caar));
    const briefResponse=await call('/api/briefs/generate',{}),brief=await briefResponse.json<{priorities:{why:string;evidenceIds:string[]}[];analysis:{reflection_sections:Record<string,string>}}>();
    expect(brief.priorities[0]?.why).toContain('Open the contact-list target first');expect(brief.priorities[0]?.evidenceIds).toContain(reflection.id);
    expect(brief.analysis.reflection_sections).toEqual({intent_and_outcome:submitted.caar.q1_today_intent,win_and_friction:submitted.caar.q2_top_win,failure_and_mechanism:submitted.caar.q3_top_failure,pattern_and_counterevidence:submitted.caar.q4_pattern_notice,tomorrow_priority:submitted.caar.q5_tomorrow_priority,if_then_plan:submitted.caar.q6_if_then_plan});
    expect(database.prepare("SELECT COUNT(*) count FROM webmcp_calls WHERE session_id=(SELECT session_id FROM missions WHERE id=?)").get(mission.id)?.count).toBe(4);
  });
  it('changes selected evidence and priorities for different reflections, including a new missed-goal adaptation',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'fixture'},initial=await worker.fetch(new Request('https://fixture.test/api/product'),env as never),cookie=initial.headers.get('set-cookie')?.split(';')[0],product=await initial.json<{missions:{id:string;horizon:string;status:string}[]}>(),today=product.missions.filter(item=>item.horizon==='today'&&item.status==='active').map(item=>item.id),call=(path:string,input:unknown)=>worker.fetch(new Request(`https://fixture.test${path}`,{method:'POST',headers:{cookie:cookie!,'content-type':'application/json'},body:JSON.stringify(input)}),env as never);
    const firstReflection=await call('/api/reflections',reflectionInput(today,'delivery')),first=await firstReflection.json<{id:string}>(),firstBrief=await (await call('/api/briefs/generate',{})).json<{priorities:{missionId:string;why:string;evidenceIds:string[]}[]}>();
    const secondInput=reflectionInput(today,'counterexample');secondInput.goal_reflections=secondInput.goal_reflections.map((item,index)=>index===0?{...item,status:'achieved' as const,why_failed:undefined,adaptation:undefined}:{...item,status:'missed' as const,why_failed:'I deferred the counterexample draft until the remaining time was too fragmented.',adaptation:'Draft the counterexample claim in the first focus block before reading more sources.'});
    const secondReflection=await call('/api/reflections',secondInput),second=await secondReflection.json<{id:string}>(),secondBrief=await (await call('/api/briefs/generate',{})).json<{priorities:{missionId:string;why:string;evidenceIds:string[]}[]}>();
    expect(first.id).not.toBe(second.id);expect(firstBrief.priorities[0]?.missionId).not.toBe(secondBrief.priorities[0]?.missionId);expect(firstBrief.priorities[0]?.evidenceIds).toContain(first.id);expect(secondBrief.priorities[0]?.evidenceIds).toContain(second.id);expect(secondBrief.priorities[0]?.why).toContain('Draft the counterexample claim');
  });
  it('returns useful field errors and rejects incomplete structured reflections',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'fixture'},response=await worker.fetch(new Request('https://fixture.test/api/reflections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({journal:'short'})}),env as never),body=await response.json<{fieldErrors:Record<string,string>}>();
    expect(response.status).toBe(400);expect(body.fieldErrors.journal).toContain('40');expect(body.fieldErrors['caar.q1_today_intent']).toContain('15');expect(body.fieldErrors.goal_reflections).toBeTruthy();
  });
  it('seeds a fresh migrated database and returns context',async()=>{
    const database=migratedDatabase();
    const response=await worker.fetch(new Request('https://fixture.test/api/context'),{...baseEnv(database),APP_MODE:'fixture'} as never);
    const body=await response.json<{historySummary?:{days:number};error?:string}>();
    expect({status:response.status,error:body.error,days:body.historySummary?.days}).toEqual({status:200,error:undefined,days:67});
    expect(Number(database.prepare('SELECT COUNT(*) count FROM events').get()?.count)).toBeGreaterThanOrEqual(20);expect(database.prepare('SELECT COUNT(*) count FROM patterns').get()?.count).toBe(3);expect(database.prepare('SELECT COUNT(*) count FROM source_chunks').get()?.count).toBe(18);expect(database.prepare('SELECT COUNT(*) count FROM council_appointments').get()?.count).toBe(3);
  });
  it('reconciles missing canonical history into an established database idempotently without rewriting authored records',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'fixture'},required=['evt-07-mum-call','evt-18-house','evt-20-depression','evt-21-house-finance','evt-38-mum-missed'];
    const initial=await worker.fetch(new Request('https://fixture.test/api/context'),env as never),cookie=initial.headers.get('set-cookie')!.split(';')[0]!;
    database.prepare(`DELETE FROM events WHERE id IN (${required.map(()=>'?').join(',')})`).run(...required);
    database.exec("INSERT INTO events(id,user_id,session_id,occurred_at,event_type,subject_id,valence,magnitude,payload_json,provenance,created_at) VALUES('evt-legacy-unrelated','demo-user',NULL,'2026-01-01T00:00:00Z','observation',NULL,'neutral',0.2,'{\"text\":\"Preserve this older unrelated event.\",\"tags\":[\"legacy\"]}','legacy-import','2026-01-01T00:00:00Z'); INSERT INTO users VALUES('other-user','Other User','2026-01-01T00:00:00Z'); INSERT INTO events(id,user_id,session_id,occurred_at,event_type,subject_id,valence,magnitude,payload_json,provenance,created_at) VALUES('evt-other-user','other-user',NULL,'2026-01-01T00:00:00Z','observation',NULL,'neutral',0.2,'{\"text\":\"Private other-user history.\",\"tags\":[\"private\"]}','user-authored','2026-01-01T00:00:00Z'); UPDATE events SET payload_json='{\"text\":\"My authored Priya correction.\",\"tags\":[\"authored\"]}',provenance='user-authored' WHERE id='evt-45-priya-draft'");
    const reconcile=()=>worker.fetch(new Request('https://fixture.test/api/context',{headers:{cookie}}),env as never);
    expect((await reconcile()).status).toBe(200);
    const rows=database.prepare(`SELECT id,user_id,session_id,event_type,occurred_at,payload_json,provenance FROM events WHERE id IN (${required.map(()=>'?').join(',')}) ORDER BY id`).all(...required) as {id:string;user_id:string;session_id:null;event_type:string;occurred_at:string;payload_json:string;provenance:string}[];
    expect(rows.map(row=>row.id)).toEqual([...required].sort());
    for(const row of rows){const payload=JSON.parse(row.payload_json) as Record<string,unknown>;expect(row).toMatchObject({user_id:'demo-user',session_id:null,provenance:'synthetic-seed-v2'});for(const field of ['text','tags','area','relationship','goalId','author','outcome'])expect(payload[field],`${row.id}.${field}`).toBeTruthy()}
    expect(database.prepare("SELECT payload_json,provenance FROM events WHERE id='evt-legacy-unrelated'").get()).toMatchObject({provenance:'legacy-import'});expect(database.prepare("SELECT payload_json,provenance FROM events WHERE id='evt-45-priya-draft'").get()).toMatchObject({payload_json:'{"text":"My authored Priya correction.","tags":["authored"]}',provenance:'user-authored'});expect(database.prepare("SELECT user_id,payload_json,provenance FROM events WHERE id='evt-other-user'").get()).toMatchObject({user_id:'other-user',payload_json:'{"text":"Private other-user history.","tags":["private"]}',provenance:'user-authored'});
    const count=Number(database.prepare('SELECT COUNT(*) count FROM events').get()?.count);expect((await reconcile()).status).toBe(200);expect(Number(database.prepare('SELECT COUNT(*) count FROM events').get()?.count)).toBe(count);for(const id of required)expect(database.prepare('SELECT COUNT(*) count FROM events WHERE id=?').get(id)?.count).toBe(1);
  });
  it('upgrades, ingests, and dual-grounds the exact serious question from reconciled non-pilot records',async()=>{
    const database=migratedDatabase(),seedEnv={...baseEnv(database),APP_MODE:'fixture'},required=['evt-07-mum-call','evt-18-house','evt-20-depression','evt-21-house-finance','evt-38-mum-missed'],question='Mum is in a dementia clinic, we are selling the family home, I have reported depression, and work is overwhelming. I feel love, guilt, and grief. Based only on my recorded history and appointed books, what is one humane next step and what can you not know?';
    await worker.fetch(new Request('https://fixture.test/api/context'),seedEnv as never);database.prepare(`DELETE FROM events WHERE id IN (${required.map(()=>'?').join(',')})`).run(...required);
    const established=database.prepare("INSERT INTO events(id,user_id,session_id,occurred_at,event_type,subject_id,valence,magnitude,payload_json,provenance,created_at) VALUES(?,'demo-user',NULL,?,'observation',NULL,'neutral',0.1,?,'legacy-import',?)");for(let index=0;index<82;index++){const day=String(index+1).padStart(2,'0'),timestamp=`2026-01-${day}T00:00:00Z`;established.run(`evt-established-${String(index).padStart(3,'0')}`,timestamp,JSON.stringify({text:`Preserved established production event ${index}.`,tags:['established'],area:'work',author:'maya',outcome:'Preserved during additive reconciliation.'}),timestamp)}
    const personal=[...required,'evt-24-urgent-counter','evt-02-client-boundary','evt-52-meaning'],ai=new CloudflareAiFixture(),env={...baseEnv(database),APP_MODE:'cloudflare',AI:ai,VECTOR_INDEX:new VectorizeFixture(personal),INGESTION_ENABLED:'true',INGESTION_KEY:'fixture-ingestion-key'};
    const ingested=await worker.fetch(new Request('https://fixture.test/api/admin/ingest-vectors',{method:'POST',headers:{authorization:'Bearer fixture-ingestion-key'}}),env as never),ingestion=await ingested.json<{personal:number;advisor:number}>(),cookie=ingested.headers.get('set-cookie')!.split(';')[0]!;
    expect(ingestion).toEqual({personal:114,advisor:18,total:132,provider:'cloudflare-workers-ai',model:'@cf/baai/bge-base-en-v1.5',dimensions:768});expect(ai.embeddingCalls.map(call=>call.length)).toEqual([100,18,14]);expect(ai.embeddingCalls.every(call=>call.length<=100)).toBe(true);for(const id of required)expect(database.prepare("SELECT COUNT(*) count FROM vector_records WHERE canonical_id=? AND corpus_kind='personal'").get(id)?.count).toBe(1);expect(database.prepare("SELECT COUNT(*) count FROM vector_records WHERE corpus_kind='personal'").get()?.count).toBe(114);expect(database.prepare("SELECT COUNT(*) count FROM vector_records WHERE corpus_kind='advisor'").get()?.count).toBe(18);expect(database.prepare("SELECT COUNT(*) count FROM events e LEFT JOIN vector_records v ON v.canonical_id=e.id AND v.corpus_kind='personal' WHERE e.user_id='demo-user' AND v.id IS NULL").get()?.count).toBe(0);expect(ingestion.personal).toBe(Number(database.prepare("SELECT COUNT(*) count FROM events WHERE user_id='demo-user'").get()?.count));
    for(const row of database.prepare("SELECT id,canonical_id FROM vector_records WHERE corpus_kind='personal'").all() as {id:string;canonical_id:string}[])expect(row.id).toBe(`vec-${row.canonical_id}`);
    const rerun=await worker.fetch(new Request('https://fixture.test/api/admin/ingest-vectors',{method:'POST',headers:{authorization:'Bearer fixture-ingestion-key',cookie}}),env as never),rerunBody=await rerun.json<{personal:number;advisor:number;total:number}>();expect(rerunBody).toMatchObject({personal:114,advisor:18,total:132});expect(database.prepare("SELECT COUNT(*) count FROM vector_records WHERE corpus_kind='personal'").get()?.count).toBe(114);expect(database.prepare("SELECT COUNT(*) count FROM vector_records WHERE corpus_kind='advisor'").get()?.count).toBe(18);
    const response=await worker.fetch(new Request('https://fixture.test/api/council',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({question})}),env as never),body=await response.json<{modelMode:string;fallbackReason:null;retrieval:{selected:{personalByAdvisor:Record<string,string[]>}};reports:{advisorId:string;abstained:boolean;claims:{personalEvidenceIds:string[];advisorEvidenceIds:string[]}[]}[];decision:{abstained:boolean;validatedReports:unknown[]};validation:{dualGrounded:boolean}}>();
    expect(ai.embeddingCalls.every(call=>call.length<=100)).toBe(true);
    expect({status:response.status,mode:body.modelMode,fallback:body.fallbackReason,dualGrounded:body.validation.dualGrounded,abstained:body.decision.abstained,reports:body.decision.validatedReports.length}).toEqual({status:200,mode:'workers-ai-structured',fallback:null,dualGrounded:true,abstained:false,reports:3});
    const lanes=body.retrieval.selected.personalByAdvisor;expect(Object.values(lanes).every(ids=>ids.length>0)).toBe(true);expect(new Set(Object.values(lanes).map(ids=>ids.join('|'))).size).toBe(3);expect(Object.values(lanes).flat().every(id=>!id.includes('pilot')&&!id.includes('priya'))).toBe(true);for(const report of body.reports){expect(report.abstained).toBe(false);expect(report.claims.every(claim=>claim.personalEvidenceIds.length>0&&claim.advisorEvidenceIds.length>0)).toBe(true)}
  });
  it('persists a valid structured Workers AI consultation with retrieval-owned canonical evidence',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'cloudflare',AI:new CloudflareAiFixture(),VECTOR_INDEX:new VectorizeFixture(),INGESTION_ENABLED:'true',INGESTION_KEY:'fixture-ingestion-key'};
    const ingested=await worker.fetch(new Request('https://fixture.test/api/admin/ingest-vectors',{method:'POST',headers:{authorization:'Bearer fixture-ingestion-key'}}),env as never),ingestion=await ingested.json<{total:number}>();expect(ingested.status).toBe(200);expect(ingestion.total).toBeGreaterThan(35);const cookie=ingested.headers.get('set-cookie')?.split(';')[0];expect(cookie).toBeTruthy();
    const memory=await worker.fetch(new Request('https://fixture.test/api/memory?q=pilot&limit=5',{headers:{cookie:cookie!}}),env as never),memoryBody=await memory.json<{retrievalMode:string;results:unknown[]}>();expect({mode:memoryBody.retrievalMode,results:memoryBody.results.length}).toEqual({mode:'workers-ai-bge768',results:5});
    const capped=await worker.fetch(new Request('https://fixture.test/api/memory?q=pilot&limit=99',{headers:{cookie:cookie!}}),env as never),cappedBody=await capped.json<{results:unknown[]}>();expect(cappedBody.results).toHaveLength(8);
    const consultation=await worker.fetch(new Request('https://fixture.test/api/council',{method:'POST',headers:{cookie:cookie!,'content-type':'application/json'},body:JSON.stringify({question:'What should I focus on in the next 45 minutes, and why?'})}),env as never),body=await consultation.json<{traceId:string;modelMode:string;model:string;modelConfigVersion:string;fallbackReason:null;retrieval:{provider:string;candidates:{personal:{id:string}[];advisor:Record<string,{id:string}[]>};selected:{personalByAdvisor:Record<string,string[]>;advisorByAdvisor:Record<string,string[]>}};evidenceProvenance:{ownership:string;interpretation:string;modelCouldSelectIdentifiers:boolean};reports:{advisorId:string;abstained:boolean;recommendation:string;counterevidenceIds:string[];evidence:{id:string;lane:string;relevance:string}[];claims:{personalEvidenceIds:string[];advisorEvidenceIds:string[]}[]}[];validation:{dualGrounded:boolean;persistent_mutation:boolean;evidenceOwnershipAccurate:boolean};decision:{abstained:boolean;validatedReports:unknown[];personalEvidenceIds:string[];advisorEvidenceIds:string[]}}>();
    expect({status:consultation.status,mode:body.modelMode,fallback:body.fallbackReason,provider:body.retrieval.provider,grounded:body.validation.dualGrounded,abstained:body.decision.abstained,validated:body.decision.validatedReports.length}).toEqual({status:200,mode:'workers-ai-structured',fallback:null,provider:'cloudflare-workers-ai-vectorize',grounded:true,abstained:false,validated:3});
    expect(body).toMatchObject({model:'@cf/openai/gpt-oss-20b',modelConfigVersion:'workers-ai-json-council-v7-gpt-oss-interactive',schemaDiagnostic:null});expect(body.evidenceProvenance).toMatchObject({ownership:'retrieval-server',interpretation:'workers-ai-generated',modelCouldSelectIdentifiers:false});expect(body.validation).toMatchObject({persistent_mutation:false,evidenceOwnershipAccurate:true});expect(new Set(body.reports.map(report=>report.recommendation)).size).toBe(3);
    expect(new Set(Object.values(body.retrieval.selected.personalByAdvisor).map(ids=>[...ids].sort().join('|'))).size).toBeGreaterThan(1);expect(body.retrieval.candidates.personal.length).toBeGreaterThanOrEqual(Math.max(...Object.values(body.retrieval.selected.personalByAdvisor).map(ids=>ids.length)));
    for(const report of body.reports){const selectedPersonal=new Set(body.retrieval.selected.personalByAdvisor[report.advisorId]),selectedAdvisor=new Set(body.retrieval.selected.advisorByAdvisor[report.advisorId]);expect(report.claims.flatMap(claim=>claim.personalEvidenceIds).every(id=>selectedPersonal.has(id))).toBe(true);expect(report.claims.flatMap(claim=>claim.advisorEvidenceIds).every(id=>selectedAdvisor.has(id))).toBe(true)}
    for(const report of body.reports){expect(report.abstained).toBe(false);expect(report.claims[0]?.personalEvidenceIds).toHaveLength(1);expect(report.claims[0]?.advisorEvidenceIds).toHaveLength(1);expect(report.evidence.every(item=>item.relevance.includes('Supplied in'))).toBe(true);for(const id of report.claims[0]!.personalEvidenceIds)expect(database.prepare("SELECT COUNT(*) count FROM events WHERE id=? AND user_id='demo-user'").get(id)?.count).toBe(1);for(const id of report.claims[0]!.advisorEvidenceIds)expect(database.prepare("SELECT COUNT(*) count FROM source_chunks sc JOIN council_appointments ca ON ca.pack_id=sc.pack_id AND ca.advisor_id=sc.advisor_id WHERE sc.id=? AND sc.advisor_id=? AND ca.user_id='demo-user' AND ca.ended_at IS NULL").get(id,report.advisorId)?.count).toBe(1)}
    const persisted=database.prepare('SELECT validation_json FROM advisor_reports WHERE consultation_id=?').all(body.traceId) as {validation_json:string}[];expect(persisted).toHaveLength(3);expect(persisted.every(row=>{const value:unknown=JSON.parse(row.validation_json);return typeof value==='object'&&value!==null&&'evidenceOwnership' in value&&value.evidenceOwnership==='retrieval-server'})).toBe(true);const audit=database.prepare("SELECT result_json FROM webmcp_calls WHERE tool_name='consult_council' ORDER BY created_at DESC LIMIT 1").get() as {result_json:string};expect(JSON.parse(audit.result_json)).toMatchObject({model:'@cf/openai/gpt-oss-20b',modelConfigVersion:'workers-ai-json-council-v7-gpt-oss-interactive',schemaDiagnostic:null,persistentMutation:false});expect(database.prepare('SELECT COUNT(*) count FROM actions').get()?.count).toBe(0);expect(database.prepare('SELECT COUNT(*) count FROM proposals').get()?.count).toBe(0);
  });
  it('handles the synthetic serious fixture before action and never mutates the plan',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'fixture'},first=await worker.fetch(new Request('https://fixture.test/api/product'),env as never),cookie=first.headers.get('set-cookie')!.split(';')[0]!,before=Number(database.prepare('SELECT COUNT(*) count FROM actions').get()?.count),response=await worker.fetch(new Request('https://fixture.test/api/council',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({question:'Mum is in a dementia clinic, we are selling the family home, I have reported depression, work is overwhelming, and I feel love, guilt, and grief. How should I understand this?'})}),env as never),body=await response.json<{reasoningRecord:{situationSummary:string;rememberedFacts:unknown[];interpretations:string[];unknowns:string[];rejectedInferences:string[];centralConflict:string;synthesis:{immediateAction:string;followUp:string;clinicalBoundary:string;unapproved:string}};reports:{advisorId:string;recommendation:string;reasoning:string;abstained:boolean}[];decision:{recommendation:string};validation:{persistent_mutation:boolean}}>();
    expect(response.status).toBe(200);expect(body).toHaveProperty('reasoningRecord');expect(body.reasoningRecord.rememberedFacts.length).toBeGreaterThan(0);expect(body.reasoningRecord.interpretations.length).toBeGreaterThan(0);expect(body.reasoningRecord.unknowns.length).toBeGreaterThan(0);expect(body.reasoningRecord.rejectedInferences.join(' ')).toMatch(/missed call.*does not prove.*love/i);expect(body.reasoningRecord.centralConflict).toMatch(/love|responsibility/i);expect(body.reasoningRecord.synthesis.clinicalBoundary).toMatch(/not treatment|human|professional/i);expect(body.reasoningRecord.synthesis.unapproved).toMatch(/nothing.*changed|not.*applied/i);expect(body.reports.find(item=>item.advisorId==='marcus-aurelius')?.recommendation).toMatch(/presence|duty|love/i);expect(body.reports.find(item=>item.advisorId==='epictetus')?.recommendation).toMatch(/illness|outcomes|blame/i);expect(body.reports.find(item=>item.advisorId==='sun-tzu')?.recommendation).toMatch(/work|workload|capacity/i);expect(body.reports.every(item=>/Limit:/i.test(item.reasoning))).toBe(true);expect(body.decision.recommendation).toMatch(/care and limits.*family member.*call time/i);expect(body.validation.persistent_mutation).toBe(false);expect(Number(database.prepare('SELECT COUNT(*) count FROM actions').get()?.count)).toBe(before);expect(Number(database.prepare('SELECT COUNT(*) count FROM proposals').get()?.count)).toBe(0);
  });
  it('fails closed before persistence when generated counsel violates scope',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'cloudflare',AI:new InvalidCouncilAiFixture(),VECTOR_INDEX:new VectorizeFixture(),INGESTION_ENABLED:'true',INGESTION_KEY:'fixture-ingestion-key'};
    const ingested=await worker.fetch(new Request('https://fixture.test/api/admin/ingest-vectors',{method:'POST',headers:{authorization:'Bearer fixture-ingestion-key'}}),env as never),cookie=ingested.headers.get('set-cookie')!.split(';')[0]!;
    const response=await worker.fetch(new Request('https://fixture.test/api/council',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({question:'Priya website message client workload'})}),env as never),body=await response.json<{traceId:string;modelMode:string;fallbackReason:string;recommendationId:string|null;recommendation:string;validation:{valid:boolean};reports:{recommendation:string}[]}>();
    expect(body.modelMode).toBe('deterministic-fallback');expect(body.fallbackReason).toBe('AI_SEMANTIC_VALIDATION_FAILED');expect(body.validation.valid,'fallback reports must validate').toBe(true);expect(body.recommendationId,'validated fallback persists').toBeTruthy();expect(body.recommendation).not.toMatch(/suppress the guilt/i);expect(body.reports.every(report=>!report.recommendation.includes('suppress the guilt'))).toBe(true);
    const stored=database.prepare('SELECT r.text,ar.validation_json FROM recommendations r JOIN advisor_reports ar ON ar.consultation_id=r.consultation_id WHERE r.consultation_id=?').all(body.traceId) as {text:string;validation_json:string}[];expect(stored).toHaveLength(3);expect(stored.every(row=>(JSON.parse(row.validation_json) as {valid:boolean}).valid===true&&row.text===body.recommendation)).toBe(true);
    const audit=database.prepare("SELECT result_json FROM webmcp_calls WHERE tool_name='consult_council' ORDER BY created_at DESC LIMIT 1").get() as {result_json:string},diagnostics=JSON.parse(audit.result_json) as {modelMode:string;model:string;modelConfigVersion:string;fallbackReason:string;modelElapsedMs:number;persistentMutation:boolean};expect(diagnostics).toMatchObject({modelMode:'deterministic-fallback',model:'@cf/openai/gpt-oss-20b',modelConfigVersion:'workers-ai-json-council-v7-gpt-oss-interactive',fallbackReason:'AI_SEMANTIC_VALIDATION_FAILED',schemaDiagnostic:null,persistentMutation:false});expect(diagnostics.modelElapsedMs).toBeGreaterThanOrEqual(0);expect(audit.result_json).not.toMatch(/messages|canonical bundle|SESSION_SIGNING_KEY/i);expect(Number(database.prepare('SELECT COUNT(*) count FROM actions').get()?.count)).toBe(0);expect(Number(database.prepare('SELECT COUNT(*) count FROM proposals').get()?.count)).toBe(0);
  });
  it('returns and audits bounded schema metadata while fallback leaves plans unchanged',async()=>{
    const database=migratedDatabase(),env={...baseEnv(database),APP_MODE:'cloudflare',AI:new MalformedCouncilAiFixture(),VECTOR_INDEX:new VectorizeFixture(),INGESTION_ENABLED:'true',INGESTION_KEY:'fixture-ingestion-key'};
    const ingested=await worker.fetch(new Request('https://fixture.test/api/admin/ingest-vectors',{method:'POST',headers:{authorization:'Bearer fixture-ingestion-key'}}),env as never),cookie=ingested.headers.get('set-cookie')!.split(';')[0]!;
    const response=await worker.fetch(new Request('https://fixture.test/api/council',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({question:'Priya website message client workload'})}),env as never),body=await response.json<{modelMode:string;fallbackReason:string;schemaDiagnostic:{issues:{path:(string|number)[];code:string}[]};validation:{persistent_mutation:boolean}}>();
    expect(body).toMatchObject({modelMode:'deterministic-fallback',fallbackReason:'AI_JSON_SCHEMA_INVALID',validation:{persistent_mutation:false}});expect(body.schemaDiagnostic.issues.length).toBeGreaterThan(0);expect(body.schemaDiagnostic.issues.length).toBeLessThanOrEqual(8);expect(JSON.stringify(body.schemaDiagnostic)).not.toMatch(/expected|received|message/i);
    const audit=database.prepare("SELECT result_json FROM webmcp_calls WHERE tool_name='consult_council' ORDER BY created_at DESC LIMIT 1").get() as {result_json:string},stored=JSON.parse(audit.result_json) as {schemaDiagnostic:unknown};expect(stored.schemaDiagnostic).toEqual(body.schemaDiagnostic);expect(database.prepare('SELECT COUNT(*) count FROM actions').get()?.count).toBe(0);expect(database.prepare('SELECT COUNT(*) count FROM proposals').get()?.count).toBe(0);
  });
});
