import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';

const base=process.env.CONSILIUM_ACCEPTANCE_URL??process.env.CONSILIUM_CAPTURE_URL;
if(!base)throw new Error('CONSILIUM_ACCEPTANCE_URL or CONSILIUM_CAPTURE_URL is required');
const output='artifacts/pass9';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true}),errors=[];
const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});page.on('pageerror',error=>errors.push(error.message));
await page.goto(`${base}/#missions`,{waitUntil:'networkidle'});let text=await page.locator('body').innerText();for(const phrase of ['Physical','Mental','Spiritual','Social','Financial','Vocational'])if(!text.includes(phrase))throw new Error(`areas missing ${phrase}`);await page.goto(`${base}/#today`,{waitUntil:'networkidle'});text=await page.locator('body').innerText();for(const phrase of ['goals for today','projects Maya is building toward'])if(!text.includes(phrase))throw new Error(`today missing ${phrase}`);
await page.goto(`${base}/#journal`,{waitUntil:'networkidle'});await page.locator('[data-dialog="reflection-dialog"]').click();text=await page.locator('#reflection-dialog').innerText();for(const phrase of ['Intent / outcome','Win','Failure without blame','Cautious pattern','One priority','If–then plan'])if(!text.includes(phrase))throw new Error(`reflection missing ${phrase}`);await page.screenshot({path:`${output}/01-desktop-six-prompts.png`,fullPage:true});await page.locator('#reflection-dialog header button').click();
const continuity=await page.evaluate(async()=>{const product=await fetch('/api/product').then(response=>response.json()),goals=product.missions.filter(mission=>mission.horizon==='today'&&mission.status==='active');const input={journal:'I finished useful client work, but I avoided one exposed question because I felt nervous about the answer.',biometrics:{sleep_hours:6.5,energy_level:6,stress_level:7,resting_hr:61},caar:{q1_today_intent:'Today I intended to finish the review and send the message, but I only finished the review.',q2_top_win:'My win was completing the review despite the difficult pull to keep checking my phone.',q3_top_failure:'I did not send the message because fear made polishing the website feel safer instead.',q4_pattern_notice:'I may polish when I fear an answer, but urgency has also helped me act directly before.',q5_tomorrow_priority:'My one honest priority tomorrow is to send the short message before opening the website.',q6_if_then_plan:'If I want to polish again tomorrow, then I will send the current draft before opening the website.'},goal_reflections:goals.map((goal,index)=>({goal_id:goal.id,status:index===0?'missed':'achieved',...(index===0?{why_failed:'I chose a safer task when the exposed action began to feel uncomfortable.',adaptation:'I will open the draft first and send it before starting any polishing.'}:{})}))};const reflection=await fetch('/api/reflections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}).then(async response=>({status:response.status,data:await response.json()}));const brief=await fetch('/api/briefs/generate',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}).then(async response=>({status:response.status,data:await response.json()}));return {reflection,brief}});if(continuity.reflection.status!==201||continuity.brief.status!==201||!continuity.brief.data.headline.includes('send the short message')||!continuity.brief.data.analysis.reflection_if_then_plan.includes('If I want to polish'))throw new Error('reflection to brief continuity failed');
await page.goto(`${base}/#brief`,{waitUntil:'networkidle'});await page.screenshot({path:`${output}/02-desktop-morning-continuity.png`,fullPage:true});
await page.goto(`${base}/#council`,{waitUntil:'networkidle'});await page.locator('#question').fill('Mum is in a dementia clinic, we are selling the family home, I have reported depression, work is overwhelming, and I feel love, guilt, and grief. How should I understand this?');await page.locator('#consult-form button').click();await page.locator('#council-result').waitFor({state:'visible'});text=await page.locator('#council-result').innerText();for(const phrase of ['WHAT I REMEMBER','WHAT MAY BE HAPPENING','WHAT I CANNOT KNOW','WHERE THEY DIFFER',"CONSILIUM'S SYNTHESIS",'ONE PROPOSED NEXT MOVE','EVIDENCE AND TRACE','does not prove that Maya does not love'])if(!text.includes(phrase))throw new Error(`council missing ${phrase}`);await page.screenshot({path:`${output}/03-desktop-serious-council.png`,fullPage:true});
const staged=await page.evaluate(async()=>{await fetch('/api/proposals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'Ask one family member to take one house-sale task.',rationale:'Staged from the serious synthesis; not applied.'})});return fetch('/api/context').then(response=>response.json())});if(staged.actions.length!==0||!staged.pending_proposal)throw new Error('proposal mutated state');const proposalId=staged.pending_proposal.id;await page.goto(`${base}/#today`,{waitUntil:'networkidle'});if(!(await page.locator('body').innerText()).includes('STAGED · APPLICATION UNCHANGED'))throw new Error('staged proposal not visible');const committedStatus=await page.evaluate(id=>fetch('/api/actions/commit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({proposal_id:id})}).then(response=>response.status),proposalId),replay=await page.evaluate(id=>fetch('/api/actions/commit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({proposal_id:id})}).then(response=>response.status),proposalId),committed=await page.evaluate(()=>fetch('/api/context').then(response=>response.json()));if(committedStatus!==200||replay!==409||committed.actions.length!==1)throw new Error('commit replay gate failed');await page.reload({waitUntil:'networkidle'});if(!(await page.locator('body').innerText()).includes('EXPLICITLY COMMITTED ACTIONS'))throw new Error('committed state not visible');
errors.splice(0,errors.length,...errors.filter(message=>!message.includes('status of 409')));await page.goto(`${base}/#trace`,{waitUntil:'networkidle'});text=await page.locator('body').innerText();if(!text.includes('13 TOOL CONTRACTS')||!text.includes('BROWSER AGENT DISCOVERY UNAVAILABLE')||!text.includes('ordinary browser'))throw new Error('WebMCP fallback disclosure missing');await page.screenshot({path:`${output}/04-desktop-webmcp-gate.png`,fullPage:true});
const desktopWidth=await page.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);await page.close();const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('console',message=>{if(message.type()==='error')errors.push(message.text())});mobile.on('pageerror',error=>errors.push(error.message));await mobile.goto(`${base}/#journal`,{waitUntil:'networkidle'});await mobile.screenshot({path:`${output}/05-mobile-journey.png`,fullPage:true});const mobileWidth=await mobile.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);await mobile.close();await browser.close();if(errors.length||desktopWidth[0]>desktopWidth[1]||mobileWidth[0]>mobileWidth[1])throw new Error(JSON.stringify({errors,desktopWidth,mobileWidth}));console.log(JSON.stringify({screenshots:5,desktopWidth,mobileWidth,reflectionStatus:continuity.reflection.status,briefStatus:continuity.brief.status,replay}));
