import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const base=process.env.CONSILIUM_CAPTURE_URL??'http://127.0.0.1:8790',output='artifacts/pass5';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true}),errors=[],page=await browser.newPage({viewport:{width:1440,height:900}});page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`)});page.on('pageerror',error=>errors.push(`page: ${error.message}`));
await page.goto(`${base}/#today`,{waitUntil:'networkidle'});await page.evaluate(()=>fetch('/api/reset',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}));await page.reload({waitUntil:'networkidle'});await page.screenshot({path:`${output}/01-desktop-today.png`,fullPage:true});
await page.goto(`${base}/#missions`);await page.screenshot({path:`${output}/02-six-areas-missions.png`,fullPage:true});
await page.locator('#view-missions [data-progress]').first().click();await page.locator('[name="progress"]').fill('74');await page.locator('[name="statusAfter"]').selectOption('active');await page.locator('[name="note"]').fill('PASS5: completed a protected block and captured the observable result.');await page.locator('#progress-form > .primary').click();
await page.goto(`${base}/#journal`);await page.locator('[data-dialog="journal-dialog"]').click();const journalArea=await page.locator('#journal-area option').last().getAttribute('value');await page.locator('#journal-area').selectOption(journalArea);const journalMission=await page.locator('#journal-mission option').nth(1).getAttribute('value');await page.locator('#journal-mission').selectOption(journalMission);await page.locator('[name="mood"]').selectOption('reflective');await page.locator('[name="body"]').fill('PASS5: Polishing felt safe, while sending the plain invitation would have tested the uncertain outcome.');await page.locator('#journal-form > .primary').click();await page.screenshot({path:`${output}/03-linked-journal-history.png`,fullPage:true});
await page.locator('[data-dialog="reflection-dialog"]').click();await page.locator('[name="sleep_hours"]').fill('5.5');await page.locator('[name="energy_level"]').fill('4');await page.locator('[name="stress_level"]').fill('8');await page.locator('[name="resting_hr"]').fill('64');await page.locator('[name="journal"]').fill('PASS5: The day produced useful evidence, but avoidance appeared when the next action became socially exposed.');for(const [index,key] of ['q1_today_intent','q2_top_win','q3_top_failure','q4_pattern_notice','q5_tomorrow_priority','q6_if_then_plan'].entries())await page.locator(`[name="${key}"]`).fill(`PASS5 answer ${index+1}: specific evidence connects today to a testable adjustment tomorrow.`);const goals=page.locator('.goal-reflection');for(let index=0;index<await goals.count();index++)await goals.nth(index).locator(`input[value="${index===0?'missed':index===1?'not_reviewed':'achieved'}"]`).check();await goals.first().locator('[name^="why_failed-"]').fill('I chose comfortable polishing after the action became socially exposed.');await goals.first().locator('[name^="adaptation-"]').fill('Open the recipient list first and send one plain invitation before polishing.');await page.locator('#reflection-form > .primary').click();await page.locator('#reflection-synthesis .synthesis').waitFor();await page.screenshot({path:`${output}/04-structured-reflection.png`,fullPage:true});await page.locator('#reflection-dialog header button').click();
await page.goto(`${base}/#brief`);await page.locator('#generate-brief').click();await page.locator('.brief-priority').first().waitFor();await page.screenshot({path:`${output}/05-evidence-morning-brief.png`,fullPage:true});
await page.goto(`${base}/#council`);await page.locator('#consult-form button').click();await page.locator('#propose').waitFor();await page.screenshot({path:`${output}/06-grounded-council-before.png`,fullPage:true});await page.locator('#propose').click();await page.locator('#commit-action').waitFor();const staged=await page.evaluate(()=>fetch('/api/context').then(r=>r.json()));if(staged.actions.length)throw new Error('proposal mutated before approval');await page.screenshot({path:`${output}/07-staged-no-mutation.png`,fullPage:true});await page.locator('#commit-action').click();await page.waitForTimeout(150);const replay=(await page.request.post(`${base}/api/actions/commit`,{headers:{cookie:(await page.context().cookies()).map(c=>`${c.name}=${c.value}`).join('; ')},data:{proposal_id:staged.pendingProposal.id}})).status();if(replay!==409)throw new Error(`replay returned ${replay}`);await page.goto(`${base}/#today`);await page.screenshot({path:`${output}/08-approved-today.png`,fullPage:true});await page.goto(`${base}/#trace`);await page.screenshot({path:`${output}/09-webmcp-trace-catalogue.png`,fullPage:true});
const desktop=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth,catalogue:document.querySelectorAll('.tool-row').length,text:document.body.innerText}));
const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('console',message=>{if(message.type()==='error')errors.push(`mobile console: ${message.text()}`)});mobile.on('pageerror',error=>errors.push(`mobile page: ${error.message}`));await mobile.goto(`${base}/#journal`,{waitUntil:'networkidle'});await mobile.locator('#menu').click();await mobile.screenshot({path:`${output}/10-mobile-navigation-history.png`,fullPage:true});const width=await mobile.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));
await browser.close();if(errors.length||desktop.body>desktop.viewport||width.body>width.viewport||!desktop.text.includes('READS')||!desktop.text.includes('STRUCTURED WRITES')||!desktop.text.includes('GATED ACTIONS'))throw new Error(JSON.stringify({errors,desktop,width}));console.log(JSON.stringify({errors,desktopWidth:desktop.body,mobileWidth:width.body,catalogue:desktop.catalogue,stagedActions:staged.actions.length,replayStatus:replay,screenshots:10}));
