import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const base=process.env.CONSILIUM_CAPTURE_URL??'http://127.0.0.1:8790',output='artifacts/pass8';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true}),errors=[];
const check=async(viewport,name,hash,phrases)=>{const page=await browser.newPage({viewport});page.on('console',m=>{if(m.type()==='error')errors.push(`${name}: ${m.text()}`)});await page.goto(`${base}/${hash}`,{waitUntil:'networkidle'});const text=await page.locator('body').innerText();for(const phrase of phrases)if(!text.includes(phrase))throw new Error(`${name} missing ${phrase}`);await page.screenshot({path:`${output}/${name}.png`,fullPage:true});const width=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));await page.close();return width};
const desktop=await browser.newPage({viewport:{width:1440,height:900}});await desktop.goto(`${base}/#council`,{waitUntil:'networkidle'});await desktop.locator('#question').fill('Mum has dementia, the family is selling her house, and depression and work feel overwhelming. How do I respond without turning this into another task?');await desktop.locator('#consult-form button').click();await desktop.locator('#council-result').waitFor({state:'visible'});const councilText=await desktop.locator('#council-result').innerText();for(const phrase of ['WHAT I REMEMBER','WHAT MAY BE HAPPENING','WHAT I CANNOT KNOW','WHERE THEY DIFFER',"CONSILIUM'S SYNTHESIS",'ONE PROPOSED NEXT MOVE','EVIDENCE AND TRACE','does not prove that Maya does not love'])if(!councilText.includes(phrase))throw new Error(`council missing ${phrase}`);await desktop.screenshot({path:`${output}/01-desktop-serious-council.png`,fullPage:true});const desktopWidth=await desktop.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));await desktop.close();
const mobileWidth=await check({width:390,height:844},'02-mobile-journal','#journal',['Mum','dementia','house','Priya','website','cancelled']);
const todayWidth=await check({width:1440,height:900},'03-desktop-today','#today',['Priya','walk','Mum']);
await browser.close();if(errors.length||[desktopWidth,mobileWidth,todayWidth].some(x=>x.body>x.viewport))throw new Error(JSON.stringify({errors,desktopWidth,mobileWidth,todayWidth}));console.log(JSON.stringify({screenshots:3,desktopWidth,mobileWidth,todayWidth}));
