const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>{const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data};
const post=(path,input={})=>api(path,{method:'POST',body:JSON.stringify(input)});
let state, council, context, registered=[],commitController;
const flash=message=>{const el=$('#flash');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',2600)};
const parse=v=>{try{return JSON.parse(v)}catch{return v}};
const date=v=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(v));
const advisorNames={'marcus-aurelius':'Marcus Aurelius',epictetus:'Epictetus','sun-tzu':'Sun Tzu'};

function route(){const view=(location.hash.slice(1)||'today').split('/')[0];$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('nav a').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#sidebar').classList.remove('open');}
window.addEventListener('hashchange',route);route();
$$('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
$$('[data-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.dialog).showModal());

const missionRows=missions=>missions.map(m=>`<div class="mission-row"><span class="tag">${esc(m.horizon)}</span><div><b>${esc(m.title)}</b><div class="progress" aria-label="${m.progress}% complete"><i style="width:${m.progress}%"></i></div><small class="muted">${m.progress}% · ${esc(m.why_text)}</small></div><button data-progress="${esc(m.id)}" data-value="${m.progress}">LOG</button></div>`).join('');
function render(){
  const active=state.missions.filter(m=>m.status==='active'),today=active.filter(m=>m.horizon==='today');
  $('#today-content').innerHTML=`<div class="panel"><p class="kicker">TODAY'S ACTIVE FRONT</p><h2>${today.length} outcomes in motion</h2>${missionRows(today)}</div><div class="panel"><p class="kicker">LAST ADAPTATION</p><h2>${esc(state.reflections[0]?.adaptation||'No reflection yet')}</h2><p class="muted">Tomorrow: ${esc(state.reflections[0]?.tomorrow||'Complete an evening reflection.')}</p></div><div class="panel wide metrics"><div class="metric"><b>${state.areas.length}</b><span>LIFE AREAS</span></div><div class="metric"><b>${active.length}</b><span>ACTIVE MISSIONS</span></div><div class="metric"><b>${state.progressLogs.length}</b><span>PROGRESS SIGNALS</span></div><div class="metric"><b>${council?.appointed?.length||0}</b><span>APPOINTED ADVISORS</span></div></div>${context?.actions?.length?`<div class="panel wide"><p class="kicker">EXPLICITLY COMMITTED ACTIONS</p>${context.actions.map(a=>`<div class="mission-row"><span class="tag">${esc(a.status)}</span><div><b>${esc(a.text)}</b><small class="muted">Audit-linked action ID ${esc(a.id)}</small></div></div>`).join('')}</div>`:''}<div class="panel wide"><p class="kicker">RECENT PERSONAL HISTORY</p>${state.progressLogs.slice(0,4).map(x=>`<div class="mission-row"><span class="tag">${esc(x.result)}</span><div><b>${esc(x.mission_title)}</b><small class="muted">${esc(x.note)} · ${date(x.occurred_at)} · ID ${esc(x.id)}</small></div></div>`).join('')}</div>`;
  $('#mission-content').innerHTML=`<div class="area-grid">${state.areas.map(a=>`<article class="area"><header><div><p class="kicker">LIFE AREA</p><h2>${esc(a.name)}</h2></div><i class="area-dot" style="background:${esc(a.accent)}"></i></header><p class="muted">${esc(a.purpose)}</p>${missionRows(state.missions.filter(m=>m.area_id===a.id))}</article>`).join('')}</div>`;
  $('#mission-area').innerHTML=state.areas.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('');
  $('#reflection-mission').innerHTML='<option value="">General day</option>'+active.map(m=>`<option value="${esc(m.id)}">${esc(m.title)}</option>`).join('');
  $('#journal-content').innerHTML=[...state.reflections.map(r=>({...r,type:'reflection'})),...state.progressLogs.map(p=>({...p,type:'progress'}))].sort((a,b)=>String(b.occurred_at).localeCompare(String(a.occurred_at))).map(x=>x.type==='reflection'?`<article class="timeline-item"><time>${date(x.occurred_at)}<br><code>${esc(x.id)}</code></time><div><p class="kicker">EVENING REFLECTION · ${esc(x.area_name||'GENERAL')}</p><h2>${esc(x.mission_title||'Whole day')}</h2><p><strong>Failure:</strong> ${esc(x.failed)}</p><p><strong>Why:</strong> ${esc(x.why_text)}</p><p><strong>Adaptation:</strong> ${esc(x.adaptation)}</p><div class="evidence">Tomorrow implication: ${esc(x.tomorrow)}</div></div></article>`:`<article class="timeline-item"><time>${date(x.occurred_at)}<br><code>${esc(x.id)}</code></time><div><p class="kicker">${esc(x.result)} · ${esc(x.area_name)}</p><h2>${esc(x.mission_title)}</h2><p>${esc(x.note)}</p><span class="tag">${x.progress}%</span></div></article>`).join('')||'<div class="empty">No history yet.</div>';
  renderBrief(state.morningBrief&&{...state.morningBrief,priorities:parse(state.morningBrief.priorities_json),evidence:parse(state.morningBrief.evidence_json),generatedAt:state.morningBrief.generated_at});
  bindProgress();renderInspector();
}
function renderBrief(b){$('#brief-content').innerHTML=!b?'<div class="empty">Generate the first brief from stored history.</div>':`<article class="brief-card"><p class="kicker">${esc(b.mode)} · ${date(b.generatedAt)}</p><h1>${esc(b.headline)}</h1>${(b.priorities||[]).map(p=>`<div class="brief-priority"><span>0${p.rank}</span><div><h2>${esc(p.title)}</h2><p>${esc(p.why)}</p><code>EVIDENCE ${esc((p.evidenceIds||[]).join(', '))}</code></div></div>`).join('')}</article><article class="brief-card"><p class="kicker">RETRIEVED MEMORY</p>${(b.evidence||[]).map(e=>`<details open><summary>${esc(e.date?date(e.date):e.id)} · ${esc(e.id)}</summary><p>${esc(e.excerpt)}</p><p class="muted">Counterevidence / failure: ${esc(e.counterevidence)}</p></details>`).join('')}</article>`}
function bindProgress(){$$('[data-progress]').forEach(b=>b.onclick=()=>{const f=$('#progress-form');f.elements.missionId.value=b.dataset.progress;f.elements.progress.value=b.dataset.value;$('#progress-dialog').showModal()})}

async function refresh(){[state,council,context]=await Promise.all([api('/api/product'),api('/api/council'),api('/api/context')]);render();renderAdvisors();syncCommitTool(context.pending_proposal)}
$('#mission-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const form=e.currentTarget,input=Object.fromEntries(new FormData(form));await post('/api/missions',input);form.reset();$('#mission-dialog').close();await refresh();flash('Mission created in D1')});
$('#progress-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const form=e.currentTarget,input=Object.fromEntries(new FormData(form));input.progress=Number(input.progress);await post('/api/progress',input);$('#progress-dialog').close();await refresh();flash('Progress evidence logged')});
$('#reflection-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const form=e.currentTarget,input=Object.fromEntries(new FormData(form));await post('/api/reflections',input);form.reset();$('#reflection-dialog').close();await refresh();flash('Reflection stored; refresh the brief to see its influence')});
$('#generate-brief').onclick=async()=>{const result=await post('/api/briefs/generate');renderBrief(result);await refresh();flash('Brief regenerated from current history')};

function renderAdvisors(){const byId=(council.sourceChunks||[]).reduce((all,x)=>{(all[x.advisorId]??=[]).push(x);return all},{});$('#advisor-content').innerHTML=Object.entries(byId).map(([id,chunks])=>{const first=chunks[0],checked=council.appointed.includes(id);return `<label class="advisor-card"><input type="checkbox" name="advisorIds" value="${esc(id)}" ${checked?'checked':''}><p class="kicker">${checked?'APPOINTED':'AVAILABLE'}</p><div class="monogram">${esc(advisorNames[id].split(' ').map(x=>x[0]).join(''))}</div><h2>${esc(advisorNames[id])}</h2><p>${esc(first.title)} · ${esc(first.translator||'verified edition')}</p><div class="source">${chunks.length} canonical passages<br>${esc(first.edition)}<br><code>${esc(first.packId)}</code></div></label>`}).join('')}
$('#appointment-form').addEventListener('submit',async e=>{e.preventDefault();const advisorIds=new FormData(e.currentTarget).getAll('advisorIds');await post('/api/council/appointments',{advisorIds});await refresh();flash('Council appointment updated')});

$('#consult-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('button',e.currentTarget),question=$('#question').value;button.disabled=true;button.textContent='RETRIEVING + DELIBERATING…';try{const result=await post('/api/council',{question});renderCouncil(result);location.hash='council'}finally{button.disabled=false;button.textContent='CONVENE COUNCIL →'}});
function reportCard(r,bundle){const personal=(r.personalEvidenceThatChangedAdvice||[]).map(id=>bundle.history?.find(x=>x.id===id)||{id});return `<article class="panel report"><p class="kicker">${esc(advisorNames[r.advisorId]||r.advisorId)}</p><h2>${esc(r.recommendation)}</h2><p>${esc(r.questionInterpreted)}</p><div class="confidence"><i style="width:${Math.round(r.confidence*100)}%"></i></div><small>Evidence quality: ${Math.round(r.confidence*100)}% · ${esc(r.uncertainty)}</small><details><summary>Personal evidence (${personal.length})</summary>${personal.map(x=>`<p><code>${esc(x.id)}</code> ${esc(x.occurredAt||'')} — ${esc(x.text||'Canonical retrieved record')}</p>`).join('')}</details><details><summary>Advisor source citations</summary>${(r.evidence||[]).filter(x=>x.lane==='advisor').map(x=>`<p><code>${esc(x.id)}</code> — ${esc(x.relevance)} · score ${Number(x.retrievalScore).toFixed(2)}</p>`).join('')}</details></article>`}
function renderCouncil(r){window.lastCouncil=r;const disagreement=(r.decision?.disagreements||r.decision?.disagreement||'Distinct lenses are preserved in the reports below.');$('#council-result').innerHTML=`<article class="brief-card"><p class="kicker">COUNCIL SYNTHESIS · ${esc(r.modelMode)}</p><h1>${esc(r.recommendation)}</h1><p>${esc(r.decision?.uncertainty||'Evidence is bounded to the retrieved records shown below.')}</p><div class="evidence">Disagreement handling: ${esc(disagreement)}</div><button class="primary" id="propose">PROPOSE THIS AS NEXT ACTION</button></article><div class="reports">${r.reports.map(x=>reportCard(x,r.evidenceBundle)).join('')}</div>`;$('#propose').onclick=async()=>{const text=r.recommendation.slice(0,240);await post('/api/proposals',{text,rationale:`Proposed from ${r.traceId}; not committed.`});await refresh();renderProposal();flash('Proposal staged; no action committed')};renderTrace(r)}
function renderTrace(r){const chunks=(council.sourceChunks||[]);$('#trace-content').innerHTML=`<article class="trace-card"><p class="kicker">RUN ${esc(r.traceId)}</p><h2>Canonical dual-grounding trace</h2><p>Pipeline <code>${esc(r.pipelineVersion)}</code> · model mode <code>${esc(r.modelMode)}</code> · mutation <b>${r.validation.persistent_mutation?'YES':'NO'}</b></p>${r.events.map(e=>`<div class="tool-row"><b>${esc(e.stage)}</b><br>${esc(e.status)} · ${esc(e.detail)}</div>`).join('')}</article>${r.reports.map(report=>`<article class="trace-card"><p class="kicker">${esc(advisorNames[report.advisorId])} · ${report.abstained?'ABSTAINED':'VALIDATED'}</p><h2>Claims and canonical evidence</h2>${report.claims.map(c=>`<details open><summary>${esc(c.claimType)} · ${esc(c.text)}</summary><p>Personal IDs: <code>${esc(c.personalEvidenceIds.join(', '))}</code></p>${c.advisorEvidenceIds.map(id=>{const x=chunks.find(y=>y.id===id);return `<div class="evidence"><code>${esc(id)}</code><br>${esc(x?.title)} · ${esc(x?.locator)}<br>“${esc(x?.excerpt)}”</div>`}).join('')}</details>`).join('')}<p><b>Uncertainty:</b> ${esc(report.uncertainty)}</p></article>`).join('')}`}
function renderProposal(){if(!context.pending_proposal)return;$('#council-result').insertAdjacentHTML('afterbegin',`<article class="brief-card"><p class="kicker">PENDING · HUMAN CONTROL GATE</p><h2>${esc(context.pending_proposal.text)}</h2><p>${esc(context.pending_proposal.rationale)}</p><button class="primary" id="commit-action">EXPLICITLY COMMIT ACTION</button></article>`);$('#commit-action').onclick=async()=>{await post('/api/actions/commit',{proposal_id:context.pending_proposal.id});await refresh();flash('Action committed and added to Today')}}

const toolDefs=[['get_current_context','Reads areas, missions, brief, actions, and pending proposal.'],['create_mission','Writes a session-scoped project or goal.'],['log_progress','Writes evidence and updates mission progress.'],['record_evening_reflection','Writes CAAR reflection and adaptation.'],['generate_morning_brief','Reads history; writes an inspectable brief.'],['appoint_council','Writes active public-domain advisor appointments.'],['consult_council','Reads personal and source evidence; writes consultation trace.'],['inspect_council_run','Reads canonical citations and validation.'],['propose_next_action','Writes a pending proposal, not an action.']];
function renderInspector(){const last=state.lastWebmcpCall;$('#tool-inspector').innerHTML=toolDefs.map(([n,d])=>`<div class="tool-row"><b>${n}</b><br>${d}</div>`).join('')+(last?`<div class="evidence"><b>LAST MUTATING CALL</b><br><code>${esc(last.tool_name)} · ${esc(last.created_at)}</code><br>Result: ${esc(last.result_json)}</div>`:'')}
const schema=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
async function register(def,options){await document.modelContext.registerTool(def,options);registered.push(def.name);$('#tool-count').textContent=`${registered.length} TOOLS`}
async function setupWebMCP(){if(!document.modelContext){$('#webmcp-status').textContent='WEBMCP UNAVAILABLE · UI ACTIVE';return}const defs=[
  {name:'get_current_context',description:toolDefs[0][1],inputSchema:schema({}),annotations:{readOnlyHint:true},execute:async()=>JSON.stringify(await api('/api/product'))},
  {name:'create_mission',description:toolDefs[1][1],inputSchema:schema({kind:{enum:['project','goal']},areaId:{type:'string'},horizon:{enum:['today','weekly','quarterly','yearly']},title:{type:'string',minLength:3,maxLength:140},why:{type:'string',minLength:3,maxLength:500},targetDate:{type:'string'}},['kind','areaId','horizon','title','why']),execute:async input=>JSON.stringify(await post('/api/missions',input))},
  {name:'log_progress',description:toolDefs[2][1],inputSchema:schema({missionId:{type:'string'},result:{enum:['progress','success','partial','failure']},progress:{type:'integer',minimum:0,maximum:100},note:{type:'string',minLength:3,maxLength:800}},['missionId','result','progress','note']),execute:async input=>JSON.stringify(await post('/api/progress',input))},
  {name:'record_evening_reflection',description:toolDefs[3][1],inputSchema:schema({missionId:{type:'string'},achieved:{type:'string'},failed:{type:'string'},happened:{type:'string'},why:{type:'string'},lesson:{type:'string'},adaptation:{type:'string'},tomorrow:{type:'string'}},['achieved','failed','happened','why','lesson','adaptation','tomorrow']),execute:async input=>JSON.stringify(await post('/api/reflections',input))},
  {name:'generate_morning_brief',description:toolDefs[4][1],inputSchema:schema({}),execute:async()=>JSON.stringify(await post('/api/briefs/generate'))},
  {name:'appoint_council',description:toolDefs[5][1],inputSchema:schema({advisorIds:{type:'array',items:{type:'string'},minItems:1,maxItems:3}},['advisorIds']),execute:async input=>JSON.stringify(await post('/api/council/appointments',input))},
  {name:'consult_council',description:toolDefs[6][1],inputSchema:schema({question:{type:'string',minLength:3,maxLength:600}},['question']),annotations:{readOnlyHint:true},execute:async({question})=>JSON.stringify(await post('/api/council',{question}))},
  {name:'inspect_council_run',description:toolDefs[7][1],inputSchema:schema({trace_id:{type:'string'}},['trace_id']),annotations:{readOnlyHint:true},execute:async({trace_id})=>JSON.stringify(await api(`/api/traces/${trace_id}`))},
  {name:'propose_next_action',description:toolDefs[8][1],inputSchema:schema({text:{type:'string',minLength:3,maxLength:240},rationale:{type:'string',maxLength:500}},['text','rationale']),execute:async input=>JSON.stringify(await post('/api/proposals',input))}
];for(const d of defs)await register(d);$('#webmcp-status').textContent='WEBMCP ACTIVE'}
async function syncCommitTool(proposal){if(!document.modelContext)return;if(commitController){commitController.abort();commitController=null;registered=registered.filter(x=>x!=='commit_proposed_action')}if(proposal){commitController=new AbortController();await register({name:'commit_proposed_action',description:'Commits the current pending proposal only after explicit human instruction.',inputSchema:schema({proposal_id:{type:'string'}},['proposal_id']),execute:async input=>JSON.stringify(await post('/api/actions/commit',input))},{signal:commitController.signal})}$('#tool-count').textContent=`${registered.length} TOOLS`}
$('#reset').onclick=async()=>{await post('/api/reset');location.reload()};
api('/api/health').then(h=>{const cloud=h.mode==='cloudflare';$('#runtime-label').textContent=cloud?'CLOUDFLARE · D1 · VECTORIZE':'LOCAL FIXTURE · D1';$('#status-dot').classList.add('live')});
setupWebMCP().then(refresh).catch(e=>{console.error(e);flash(e.message)});
